### ISSUE TITLE
Adjusting big CPU frequency seems to be bugged.

### ISSUE THREAD

**Issue by Renkyz** [xxmustafacooTR/KernelManager#1]
The option to adjust the big CPU frequency doesn't appear to be working.
If say for example, the default value is 1500mhz and I choose to increase it to 2000mhz, the change automatically reverts itself in a second or so. The device being used is a Note 9 N960F with NOBLE ROM 4.2 Calabria III, with the xxmustafacooTR Kernel V46.0 for exynos9810 (S9,S9+N9) EMS version.

**Comment by dyrok** [comment]
Same is occuring with me please assign someone.

**Comment by xxmustafacooTR** [comment]
Do you guys tried changing quad hotplug freq? or trying another cpu governor because cpu governor and hotplug governor also controls big cpu freqs. Little cpu should be ok.

**Comment by dyrok** [comment]
just flash the orignal 
xxtr kernel appolo's does not support changing the big cpu frequencies
